version: 2

services:
    syncthing:
      image: lscr.io/linuxserver/syncthing:latest
      container_name: syncthing
      hostname: syncthing #optional
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
      volumes:
        - /data/podman/syncthing/config
        - /data/podman/syncthing/data1
        - /data/podman/syncthing/data2
      ports:
        - 8384:8384
        - 22000:22000/tcp
        - 22000:22000/udp
        - 21027:21027/udp
      restart: unless-stopped

    jellyfin:
    image: jellyfin/jellyfin
      container_name: jellyfin
      user: uid:gid
      network_mode: 'host'
      volumes:
        - /data/podman/jelly/config
        - /data/podman/jelly/cache
        - /data/podman/jelly/media
        - /data/podman/jelly/media2
      restart: 'unless-stopped'
      # Optional - alternative address used for autodiscovery
      environment:
        - JELLYFIN_PublishedServerUrl=http://example.com
      # Optional - may be necessary for docker healthcheck to pass if running in host network mode
      extra_hosts:
        - "host.docker.internal:host-gateway"

    homeassistant:
      image: lscr.io/linuxserver/homeassistant:latest
      container_name: homeassistant
      network_mode: host
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
      volumes:
        - /data/podman/hassio/config
      ports:
        - 8123:8123 #optional
      devices:
        - /data/podman/hassio/device #optional
      restart: unless-stopped
