version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      -  /home/jenot/hass/config:/config
    ports:
      - 8123:8123 #optional

    labels:
    - "io.containers.autoupdate=registry"
    restart: unless-stopped