## infra bratku

version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_database_USER}
      - GITEA__database__PASSWD=${GITEA_database_PASSWD}
    restart: always
    networks:
      - gitea
    volumes:
      - /srv/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${mySQL_root_PASSWD}
      - MYSQL_USER=${GITEA_database_USER}
      - MYSQL_PASSWORD=${GITEA_database_PASSWD}
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /srv/gitea/db:/var/lib/mysql

# Make ur own secrets
