---
  name: Install and maintain stuff
  hosts: Hoelab
  become: yes
  vars_files:
    - vars.yml
  tasks:

  - name: Install packages
    dnf:
      name: "{{ packages }}"
      state: present

  - name: Update packages
    dnf:
      name: "*"
      state: latest
      update_cache: yes