---
- name: Install packages and maintain them on storage host
  hosts: storage
  become: true

  vars:
    packages:
      - vim
      - git
      - neofetch
      - htop
      - ufw
      - samba
      - libsensors-dev

  tasks:
    - name: Check updates
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true
        force_apt_get: true
        dpkg_options: 'force-confdef,force-confold'
        update_cache: true
        cache_valid_time: 3600

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Install packages and maintain them on infra host
  hosts: infra
  become: true

  vars:
    packages:
      - vim
      - git
      - neofetch
      - htop
      - ufw
      - libsensors-dev


  tasks:
    - name: Check updates
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true
        force_apt_get: true
        dpkg_options: 'force-confdef,force-confold'
        update_cache: true
        cache_valid_time: 3600

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
