---
- name: Modify SSH configuration to only allow login with SSH keys
  hosts: hoelab
  become: true

  tasks:
    - name: Ensure only SSH key login is allowed
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart sshd

  handlers:
    - name: Restart sshd service
      ansible.builtin.systemd:
        name: sshd
        state: restarted
