version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - JELLYFIN_PublishedServerUrl=192.168.0.29 #optional
    volumes:
      -  /data/podman/jelly/config:/config
      - /data/podman/jelly/media/tvshows:/data/tvshows
      - /data/podman/jelly/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    labels:
    - "io.containers.autoupdate=registry"
    restart: unless-stopped