name: "Ansbile Lint"
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: run-ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.2.0
